name: Node.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - name: create dist files
        run: |
          npm ci
          npm run lint:prettier-check
          npm run webpack
      - name: Archive generated files
        uses: actions/upload-artifact@v2
        with:
          name: google-date-range-search
          path: dist
